const report=__DATA__,meta=report.metadata,assets=report.assets,grid=report.grid,annual=report.annual,findings=report.findings;
const el=id=>document.getElementById(id),pct=x=>x==null?'—':(100*x).toFixed(2)+'%',pp=x=>x==null?'—':(x>=0?'+':'')+(100*x).toFixed(2)+' pp',money=x=>x==null?'—':'$'+x.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}),num=x=>x==null?'—':x.toLocaleString('en-US',{maximumFractionDigits:4}),cls=x=>x<0?'negative':'positive';
const labels=meta.labels,policies=meta.policies,rules=meta.rules,loading=new Map();let selectedSymbol='BTC/USD',generation=0,detailGeneration=0,activeRows=null,activeKey=null;
const layout={paper_bgcolor:'white',plot_bgcolor:'white',font:{family:'Segoe UI,system-ui,sans-serif',size:11,color:'#536d72'},margin:{l:65,r:15,t:45,b:45},hovermode:'x unified',legend:{orientation:'h',x:0,y:1.16},xaxis:{showgrid:false},yaxis:{gridcolor:'#e7efea',tickformat:'.2s'}};
const plotConfig={responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d']};
const lookup=(key,cost='normal',scope=el('scope').value,period='validation')=>grid.find(r=>r.scenario===key&&r.cost===cost&&r.scope===scope&&r.period===period);
el('scope').innerHTML=report.scopes.map(s=>`<option>${s}</option>`).join('');
el('cost').querySelector('option[value="gross"]').remove();
el('strategy').innerHTML=policies.map(k=>`<option value="${k}">${labels[k]}</option>`).join('')+'<optgroup label="Other fixed neighbourhood settings">'+rules.filter(r=>!policies.includes(r.id)).map(r=>`<option value="${r.id}">${r.label}</option>`).join('')+'</optgroup>';
el('strategy').value='e20-x55-s3';el('symbol').innerHTML=assets.map(s=>`<option>${s.symbol}</option>`).join('');el('symbol').value=selectedSymbol;
el('stamp').textContent=`${meta.symbol_count} assets · ${meta.account_scenarios.toLocaleString()} account scenarios · ${meta.generated_utc.slice(0,10)} UTC`;
el('top-cards').innerHTML=[['Full-universe coverage',meta.symbol_count,'Every stored asset'],['Chronological evaluation',meta.validation_assets,`${meta.symbol_count-meta.validation_assets} have insufficient training history`],['Long neighbourhood',54,'Fixed grid · no Chandelier'],['Cost scenarios','1× / 2×','Same choices, same fills']].map(([a,b,c])=>`<div class="card"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('');
el('decision-rows').innerHTML=policies.map(key=>{const a=lookup(key,'normal','Priority assets'),b=lookup(key,'double','Priority assets'),whole=lookup(key,'normal','Whole universe');return `<tr data-key="${key}" class="${key==='baseline-short'?'benchmark':''}"><td class="key-label"><b>${labels[key]}</b>${key==='baseline-short'?'<small>Fixed short reference · not tuned</small>':''}</td><td class="${cls(a.median_cagr)}">${pct(a.median_cagr)}</td><td>${pct(b.median_cagr)}</td><td>${pct(a.median_drawdown)}</td><td>${a.positive}/${a.assets}</td><td>${whole.positive}/${whole.assets}</td></tr>`}).join('');
el('decision-rows').querySelectorAll('tr').forEach(t=>t.onclick=()=>select(t.dataset.key));
const paired=findings.class_comparison.find(r=>r.scope==='Priority assets'&&r.cost==='normal'),decisionNote=document.createElement('p');decisionNote.className='notice';decisionNote.textContent=`Class-specific annual selection raises the aggregate median, but improves CAGR on ${paired.higher_cagr} of ${paired.assets} priority assets. The median paired CAGR change is ${pp(paired.median_cagr_difference)}, with positive median improvement in ${paired.positive_completed_folds} of ${paired.completed_folds} completed years. That is not consistent evidence that each class needs separate settings.`;el('decision-rows').closest('.table-wrap').after(decisionNote);
el('class-rows').innerHTML=findings.class_comparison.filter(r=>r.scope!=='Whole universe').map(r=>`<tr><td>${r.scope}<small>${r.cost==='normal'?'Normal':'Doubled'} costs</small></td><td class="${cls(r.median_cagr_difference)}">${pp(r.median_cagr_difference)}</td><td>${r.higher_cagr}/${r.assets}</td><td>${r.less_drawdown}/${r.assets}</td><td>${r.positive_completed_folds}/${r.completed_folds}</td></tr>`).join('');
el('selection-rows').innerHTML=Object.entries(report.selections).map(([year,groups])=>`<tr><td>${year}${year==='2026'?' · partial':''}<small>Train ${Number(year)-3}–${Number(year)-1}</small></td>${['Common','Equities and other ETFs','Bonds','Crypto'].map(g=>`<td class="key-label">${labels[groups[g].rule]}<small>${groups[g].fallback?'Common fallback':groups[g].group_members+' training assets'}</small></td>`).join('')}</tr>`).join('');
el('neighbour-rows').innerHTML=findings.neighbourhoods.map(r=>`<tr><td>${labels[r.anchor]}<small>${r.cost==='normal'?'Normal':'Doubled'} costs</small></td><td>${pct(r.minimum)}</td><td>${pct(r.median)}</td><td>${pct(r.maximum)}</td><td>${r.positive}/${r.count}</td></tr>`).join('');
el('source-rows').innerHTML=report.second_source.comparisons.flatMap(s=>Object.entries(s.rules).map(([key,bySource])=>{const a=bySource.Coinbase.validation.normal.stats,b=bySource.Bitstamp.validation.normal.stats;return `<tr><td>${s.symbol}<small>${labels[key]}</small></td><td>${pct(a.cagr)}</td><td>${pct(b.cagr)}</td><td>${pct(a.drawdown)}</td><td>${pct(b.drawdown)}</td></tr>`})).join('');
el('source-note').textContent=report.second_source.comparisons.map(s=>`${s.symbol}: ${s.matched_days} matched days (${s.start} to ${s.end}); median close-price difference ${pct(s.median_close_difference)}, 95th percentile ${pct(s.p95_close_difference)}. ${s.coinbase_days_not_matched} Coinbase days unmatched.`).join(' ');
el('checks').textContent=`All ${meta.fill_bridge_checks.toLocaleString()} full-history fixed-rule runs reproduce existing-engine fills. The independent cash simulator checks ${meta.cash_audit_bars.toLocaleString()} daily observations, including normal/doubled costs and annual rule changes; maximum relative difference ${meta.cash_max_error.toExponential(2)}. Every dollar ledger reconciles; maximum aggregate discrepancy $${meta.identity_max_error.toExponential(2)}. The production engine and Step 3 cash calculation are unchanged.`;
el('hash').textContent=`Production engine: ${meta.engine_sha256} | Cash accounting: ${meta.cash_sha256} | Frozen inputs: ${meta.inputs_sha256}`;
el('checks').insertAdjacentHTML('afterend','<p class="note"><a href="verification.json">Saved-ledger and past-only selection verification</a></p>');

function select(key){el('strategy').value=key;el('period').value='validation';refresh()}
function renderCharts(){const scope=el('scope').value,cost=el('cost').value;
 const traces=['normal','double'].map((c,i)=>({type:'bar',x:policies.map(k=>100*lookup(k,c).median_cagr),y:policies.map(k=>labels[k]),orientation:'h',name:i?'Doubled costs':'Normal costs',marker:{color:i?'#99bfb1':'#168778'},hovertemplate:'%{y}<br>%{x:.2f}% median CAGR<extra></extra>'}));
 Plotly.react('strategy-bars',traces,{...layout,margin:{l:225,r:20,t:35,b:50},barmode:'group',hovermode:'closest',xaxis:{title:{text:'Median calendar CAGR (%)'},zerolinecolor:'#9caeaa'},yaxis:{autorange:'reversed',tickfont:{size:10}}},plotConfig);
 const years=meta.years;const matrix=policies.map(k=>years.map(y=>annual.find(r=>r.scope===scope&&r.scenario===k&&r.cost===cost&&r.year===y)));
 Plotly.react('annual',[{type:'heatmap',x:years.map(y=>y===2026?'2026 partial':String(y)),y:policies.map(k=>labels[k]),z:matrix.map(row=>row.map(r=>r?100*r.median_net:null)),text:matrix.map(row=>row.map(r=>r?`${pct(r.median_net)} · ${r.assets} assets`:'No eligible history')),hovertemplate:'%{y}<br>%{x}<br>%{text}<extra></extra>',colorscale:[[0,'#b25261'],[.5,'#faf7ee'],[1,'#188777']],zmid:0,showscale:false}],{...layout,margin:{l:225,r:15,t:20,b:45},hovermode:'closest',xaxis:{type:'category'},yaxis:{type:'category',autorange:'reversed',tickfont:{size:10}}},plotConfig);
 const entries=[5,10,15,20,25,30],exits=[40,55,70],stop=el('stop').value;
 const cells=exits.map(x=>entries.map(e=>lookup(`e${e}-x${x}-s${stop}`,cost)));
 Plotly.react('neighbours',[{type:'heatmap',x:entries.map(String),y:exits.map(String),z:cells.map(row=>row.map(r=>100*r.median_cagr)),text:cells.map(row=>row.map(r=>pct(r.median_cagr))),texttemplate:'%{text}',customdata:exits.map(x=>entries.map(e=>`e${e}-x${x}-s${stop}`)),colorscale:[[0,'#b25261'],[.5,'#faf7ee'],[1,'#188777']],zmid:0,showscale:false,hovertemplate:'Entry %{x}, exit %{y}<br>%{text}<extra></extra>'}],{...layout,margin:{l:65,r:15,t:35,b:60},hovermode:'closest',xaxis:{type:'category',title:{text:'Entry lookback (bars)'}},yaxis:{type:'category',autorange:'reversed',title:{text:'Channel exit (bars)'}}},plotConfig);
 el('neighbours').removeAllListeners?.('plotly_click');el('neighbours').on('plotly_click',e=>select(e.points[0].customdata));
}
function loadScript(path){if(!loading.has(path))loading.set(path,new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=path;script.onload=resolve;script.onerror=reject;document.body.appendChild(script)}));return loading.get(path)}
function current(symbol=selectedSymbol){return activeRows?.[symbol]?.[el('period').value]?.[el('cost').value]}
async function refresh(){const token=++generation,key=el('strategy').value;if(key.startsWith('adaptive-'))el('period').value='validation';renderCharts();el('table-sub').textContent='Loading '+labels[key]+'…';try{await loadScript('candidates/'+key+'.js')}catch(e){el('table-sub').textContent='Could not load candidate data.';return}if(token!==generation)return;activeRows=window.step5Rows[key];activeKey=key;renderTable();renderDetail()}
function renderTable(){if(activeKey!==el('strategy').value)return;const text=el('search').value.toUpperCase(),view=assets.filter(s=>s.symbol.includes(text));
 el('table-sub').textContent=`${view.length} of ${assets.length} stored assets · ${labels[activeKey]}`;
 el('view-note').textContent=el('period').value==='validation'?'Evaluation starts flat in the first eligible test year for each asset. All strategies share that start date.':'Full-history simulation includes the native warm-up and all available stored dates; it is separate from chronological validation.';
 el('asset-rows').innerHTML=view.map(s=>{const data=current(s.symbol),r=data?.stats;return `<tr data-symbol="${s.symbol}" class="${s.symbol===selectedSymbol?'selected':''}"><td><b>${s.symbol}</b>${s.priority?' <span class="badge">Priority</span>':''}<small>${s.asset_class}</small>${r&&r.days<730.5?'<small>Less than 2 years of evaluation</small>':''}</td>${r?`<td class="${cls(r.net)}">${pct(r.net)}</td><td>${pct(r.cagr)}</td><td>${pct(r.drawdown)}</td><td>${r.trades}${r.trades<5?' · thin':''}</td><td>${r.start} → ${r.end}</td><td>${money(r.ending)}</td>`:'<td colspan="6">Insufficient preceding training history · full-history results available</td>'}</tr>`}).join('');
 el('asset-rows').querySelectorAll('tr').forEach(t=>t.onclick=()=>{selectedSymbol=t.dataset.symbol;el('symbol').value=selectedSymbol;renderTable();renderDetail();el('instrument-panel').scrollIntoView({behavior:'smooth'})});
}

async function renderDetail(){const token=++detailGeneration,symbol=selectedSymbol,key=el('strategy').value,period=el('period').value,cost=el('cost').value,asset=assets.find(s=>s.symbol===symbol),r=current()?.stats;
 el('instrument-title').textContent=symbol+' · '+labels[key];el('instrument-meta').textContent=r?`${r.start} → ${r.end} · ${period==='full'?'Full available history':'Chronological evaluation'} · ${cost==='normal'?'Normal':'Doubled'} costs`:'';
 el('unavailable').classList.toggle('hidden',Boolean(r));el('unavailable').textContent='This asset has insufficient preceding history for the three-year training window. Select full available history to inspect its fixed-strategy results.';el('instrument-content').classList.toggle('hidden',!r);if(!r)return;
 let data;try{await loadScript('instruments/'+symbol.replace('/','_')+'.js');data=await window.step5Ready[symbol]}catch(e){el('instrument-meta').textContent='Could not decode the instrument data. Keep the instruments folder beside the report.';return}
 if(token!==detailGeneration||key!==el('strategy').value||symbol!==selectedSymbol)return;
 const v=data.variants[key][period];
 el('instrument-cards').innerHTML=[['Net total return',pct(r.net)],['Calendar CAGR',pct(r.cagr)],['Maximum drawdown',pct(r.drawdown)],['Closed trades',r.trades]].map(([a,b])=>`<div class="card"><span>${a}</span><strong>${b}</strong></div>`).join('');
 const traces=[['normal','Normal costs','#168778'],['double','Doubled costs','#b36f65'],['gross','Zero costs','#b28b3d']].map(([c,name,color])=>({type:'scatter',mode:'lines',x:v.dates,y:v.curves[c],name,line:{color,width:2,dash:c==='gross'?'dot':'solid'}}));
 for(const other of policies){if(other===key||!data.variants[other]?.[period])continue;const d=data.variants[other][period];traces.push({type:'scatter',mode:'lines',x:d.dates,y:d.curves[cost],name:labels[other],visible:'legendonly',line:{width:1.3}})}
 Plotly.react('equity',traces,{...layout,yaxis:{...layout.yaxis,title:{text:'Account value ($)'}},uirevision:symbol+'|'+key+'|'+period},plotConfig);
 el('money-equation').textContent=`$10,000 ${r.price_pnl>=0?'+':'−'} ${money(Math.abs(r.price_pnl))} price P&L − ${money(r.fees)} fees − ${money(r.slippage)} slippage ≈ ${money(r.ending)}`;
 el('calendar-equation').textContent=r.cagr==null?'CAGR is unavailable after account exhaustion.':`CAGR = (${money(r.ending)} / $10,000)^(1 / ${(r.days/365.25).toFixed(3)} calendar years) − 1 = ${pct(r.cagr)}. Time in cash is included. ${period==='validation'?'This account starts at the first eligible test year, rather than at the beginning of the full price history.':''}`;
 const yearly=current().years;
 el('policy-years').innerHTML='<table><thead><tr><th>Year</th><th>Rule for new signals</th><th>Net return</th><th>Drawdown</th><th>Closed trades</th></tr></thead><tbody>'+Object.entries(yearly).map(([year,s])=>`<tr><td>${year}${year==='2026'?' · partial':''}</td><td class="key-label">${labels[asset.schedules?.[key]?.[year]||key]}</td><td>${pct(s.net)}</td><td>${pct(s.drawdown)}</td><td>${s.trades}</td></tr>`).join('')+'</tbody></table>';
 const ledger=v.ledgers[cost];el('ledger-note').textContent=`${ledger.length} funded trades including any open or exhaustion mark. Newest first. Dollar calculations retain full precision. The downloadable CSV also records the actual entry rule retained by each trade.`;
 el('trade-rows').innerHTML=[...ledger].reverse().map(t=>`<tr><td>${t[0]}<small>${t[1]}</small></td><td>${num(t[2])}</td><td>${num(t[4])}</td><td>${t[12]}<small>${t[5]}</small></td><td>${num(t[6])}</td><td>${money(t[7])}</td><td class="${cls(t[8])}">${money(t[8])}</td><td>${money(t[9])}</td><td>${money(t[10])}</td><td>${money(t[11])}</td></tr>`).join('');
 const partition=key.startsWith('adaptive-')?'adaptive':key.startsWith('baseline-')?'baseline':key.split('-')[0];el('ledger-download').href='trades-'+partition+'.csv.gz';el('ledger-download').textContent=`Download ${partition} ledgers · includes both cost levels and all saved periods ↗`;
}
for(const id of ['scope','cost','strategy','period'])el(id).onchange=refresh;
el('stop').onchange=renderCharts;el('search').oninput=renderTable;
el('symbol').onchange=()=>{selectedSymbol=el('symbol').value;renderTable();renderDetail()};
refresh();
