async (page) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const check = (ok, text) => { if (!ok) throw new Error(text); };
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Refresh saved data'}).click();
  await page.getByText('60 eligible assets, including flat names',{exact:true}).waitFor();
  await page.screenshot({path:'H:/ai/trade-helper-v2/docs/temp/integration/sizing-today.png',fullPage:true});
  await page.getByRole('tab',{name:'Historical simulation'}).click();
  await page.getByText('12.59%',{exact:true}).waitFor();
  check(await page.getByText('-18.27%',{exact:true}).count() > 0,'Default drawdown');
  await page.getByRole('checkbox',{name:'Show long trades'}).uncheck();
  check(await page.getByText('12.59%',{exact:true}).count() > 0,'Display filter changed equity');
  check(await page.getByText(/0 matching trades/).count() > 0,'Long filter did not hide ledger');
  await page.getByRole('checkbox',{name:'Show long trades'}).check();
  await page.screenshot({path:'H:/ai/trade-helper-v2/docs/temp/integration/sizing-history.png',fullPage:true});
  await page.getByRole('combobox',{name:'Allocation direction',exact:true}).click();
  await page.getByRole('option',{name:'Long + short · 50/50',exact:true}).click();
  await page.getByText(/Controls differ from the displayed result/).waitFor();
  const replyPromise=page.waitForResponse(r=>r.url().endsWith('/api/sizing/run')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Run portfolio simulation'}).click();
  const reply=await (await replyPromise).json();
  await page.getByRole('progressbar').waitFor();
  await page.getByRole('button',{name:'Run portfolio simulation'}).waitFor({state:'visible'});
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('button')).some(b=>b.textContent==='Run portfolio simulation'&&!b.disabled),{},{timeout:60000});
  await page.getByText('5.54%',{exact:true}).waitFor();
  check(await page.getByText(/Controls differ from the displayed result/).count()===0,'Completed result still dirty');
  await page.getByRole('tab',{name:'Allocation today'}).click();
  check(await page.getByRole('cell',{name:'short',exact:true}).count()>0,'Combined fresh allocation has no short rows');
  await page.setViewportSize({width:390,height:844});
  const hide=page.getByRole('button',{name:/Hide sidebar/});
  if(await hide.count())await hide.click();
  await page.waitForTimeout(600);
  const widths=await page.evaluate(()=>({window:innerWidth,document:document.documentElement.scrollWidth}));
  await page.screenshot({path:'H:/ai/trade-helper-v2/docs/temp/integration/sizing-mobile.png',fullPage:true});
  check(widths.document<=widths.window+2,'Sizing mobile page overflow '+JSON.stringify(widths));
  check(errors.length===0,errors.join('\n'));
  return {defaultCagr:'12.59%',combinedCagr:'5.54%',combinedRun:reply.run_id,displayFiltersPreserveEquity:true,widths,errors};
}
