"""Interactive Step 1 report with local per-instrument data and embedded Plotly."""
import json

from plotly.offline import get_plotlyjs


def write_report(result, path):
    payload = json.dumps(result, ensure_ascii=False, allow_nan=False).replace("<", "\\u003c")
    path.write_text(TEMPLATE.replace("__PLOTLY__", get_plotlyjs()).replace("__DATA__", payload), encoding="utf-8")


TEMPLATE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Step 1 · Trading baseline</title><link rel="icon" href="data:,">
<style>
:root{--ink:#142a32;--muted:#64767a;--teal:#087f7a;--red:#bc4b49;--line:#dfe7e4;--paper:#f5f7f3;--orange:#bb7a28}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}
header{background:#122d35;color:#fff;padding:36px max(28px,calc((100vw - 1320px)/2));border-bottom:5px solid #57c1af}
.eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:11px;font-weight:750;color:#9cdbca;margin-bottom:12px}
h1{font-size:clamp(28px,4vw,42px);line-height:1.16;letter-spacing:-1.3px;margin:0 0 12px}header p{max-width:860px;color:#c0d0d1;margin:0;font-size:16px}
.header-bottom{display:flex;gap:20px;align-items:center;justify-content:space-between;margin-top:26px;font-size:12px;color:#b7cccb}.header-bottom a{color:#cfede5;margin-left:18px;text-decoration:none}
main{max-width:1376px;margin:0 auto;padding:26px 28px 60px}h2{font-size:22px;letter-spacing:-.5px;margin:0 0 5px}h3{font-size:15px;margin:0 0 10px}p{margin:8px 0}.sub{color:var(--muted);font-size:13px}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:20px}.kpi{background:#fff;border:1px solid var(--line);border-radius:12px;padding:20px}.kpi .label{color:var(--muted);font-size:12px}.kpi strong{font-size:33px;font-weight:650;letter-spacing:-1px;display:block;line-height:1.3}.kpi small{font-size:11px;color:var(--muted)}
.notice{border-left:4px solid var(--orange);background:#fff6e6;padding:15px 18px;border-radius:0 9px 9px 0;margin-bottom:26px;font-size:13px}.notice b{color:#82551c}
.panel{background:#fff;border:1px solid var(--line);border-radius:13px;padding:24px;margin-bottom:22px}.panel-top{display:flex;justify-content:space-between;gap:16px;align-items:start}.controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap}select,input,button{font:inherit;border:1px solid #cad8d4;border-radius:7px;padding:8px 11px;background:#fff;color:var(--ink)}button{cursor:pointer}button:hover{background:#eef6f2}input[type=checkbox]{accent-color:var(--teal)}label{font-size:12px}.chart{height:370px;width:100%}.ddchart{height:195px}.annualchart{height:280px}
.detail-cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:20px 0}.detail-card{padding:13px 16px;background:#f5f8f6;border-radius:8px}.detail-card span{display:block;font-size:11px;color:var(--muted)}.detail-card b{font-size:21px;font-weight:650}.positive{color:var(--teal)}.negative{color:var(--red)}.note{font-size:12px;color:var(--muted);margin-top:12px}
.two{display:grid;grid-template-columns:1fr 1fr;gap:22px}.table-wrap{overflow:auto;margin-top:18px}table{border-collapse:collapse;width:100%;font-size:12px;font-variant-numeric:tabular-nums}th{background:#f3f7f5;color:#53686a;text-align:right;font-size:10px;text-transform:uppercase;letter-spacing:.04em;white-space:nowrap;padding:12px 10px;cursor:pointer}td{padding:12px 10px;border-bottom:1px solid #e8eeeb;text-align:right;white-space:nowrap}th:first-child,td:first-child{text-align:left}td.asset{font-weight:700;color:#183f47}td small{display:block;color:var(--muted);font-weight:400;font-size:10px}.asset-table tr:hover td{background:#f1f8f5;cursor:pointer}.asset-table tr.selected td{background:#e6f3ee}.chip{display:inline-block;font-size:10px;padding:3px 8px;border-radius:12px;background:#e4f3ed;color:#226958}
.reading{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.reading p{font-size:13px;color:#53696d}.reading strong{display:block;color:var(--ink);font-size:14px;margin-bottom:5px}details{border-top:1px solid var(--line);padding-top:16px;margin-top:20px;font-size:12px;color:var(--muted)}summary{cursor:pointer;color:var(--ink);font-weight:600}.params{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.params div{padding:8px;background:#f4f7f5;border-radius:5px}.params b{color:var(--ink)}.checks{font-size:12px;color:var(--muted);margin-top:15px}footer{text-align:center;color:var(--muted);font-size:12px;padding-top:12px}a{color:var(--teal)}.badges{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}
@media(max-width:900px){.kpis{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}.detail-cards{grid-template-columns:repeat(3,1fr)}.reading{grid-template-columns:1fr}.panel-top{flex-direction:column}.header-bottom{align-items:start;flex-direction:column}.header-bottom a{margin:0 16px 0 0}}
@media(max-width:550px){main{padding:18px 12px}.panel{padding:16px}.detail-cards{grid-template-columns:repeat(2,1fr)}.kpi{padding:14px}.kpi strong{font-size:27px}.params{grid-template-columns:1fr 1fr}.chart{height:320px}}
@media print{header{background:white;color:#142a32}.header-bottom,header p{color:#53696d}body{background:white}.panel{break-inside:avoid}.controls{display:none}main{padding:10px}.table-wrap{overflow:visible}}
</style></head><body>
<header><div class="eyebrow">Trading research · 01 / Baseline</div><h1>The strategy we have today.</h1>
<p>A measured starting point for the next experiment: current entries, current exits, both directions, and the prices now stored in the app.</p>
<div class="header-bottom"><span id="stamp"></span><nav><a href="summary.csv" download>Summary CSV ↗</a><a href="trades.csv" download>Trade ledger ↗</a><a href="details.zip" download>Full curves &amp; trades ZIP ↗</a></nav></div></header>
<main><section class="kpis" id="kpis"></section>
<div class="notice"><b>Cost assumptions need your execution setup.</b> The baseline uses each assigned strategy’s configured costs: currently 5 bps + 0.05 ATR on each fill. Crypto shorts are hypothetical spot-price short exposure; borrowing, perpetual funding and liquidation are not modelled. These results do not establish the return of a particular broker or futures contract.</div>
<section class="panel"><div class="panel-top"><div><h2 id="asset-title">Instrument review</h2><div class="sub" id="asset-meta"></div></div><div class="controls"><select id="symbol" aria-label="Instrument"></select><label><input type="checkbox" id="log" checked> Log scale</label></div></div>
<div class="badges" id="badges"></div><div id="instrument-warning" class="notice" style="margin-top:14px" hidden></div><div class="detail-cards" id="detail-cards"></div>
<div class="chart" id="equity"></div><div class="ddchart" id="drawdown"></div>
<div class="note">Start value = 100. Buy &amp; hold is before execution costs; strategy net includes modelled fill costs. Click a legend item to hide or show it. Long / short contribution lines use the same two-sided trade sequence; they are not standalone one-direction strategies.</div>
<details><summary>Exact rules and accounting for this instrument</summary><div id="params" class="params"></div><p id="accounting"></p></details></section>
<div class="two"><section class="panel"><h2>Where the return came from</h2><div class="sub">Calendar-year returns; first and last years may be partial.</div><div class="annualchart" id="annual"></div><p class="note" id="cost-note"></p></section>
<section class="panel"><h2>Long and short, separately</h2><div class="sub">Contributions to this instrument’s two-sided run.</div><div class="table-wrap" id="sides"></div><h3 style="margin-top:24px">What closed the trades?</h3><div id="exits"></div><p class="note" id="recovery"></p></section></div>
<section class="panel"><div class="panel-top"><div><h2>The whole-database baseline</h2><div class="sub">Every instrument with stored OHLC, including shorter histories. Click a row to explore it above. Headline counts follow the filters.</div></div><div class="controls"><select id="scope" aria-label="Universe"><option value="all">Whole database</option><option value="watchlist">Original 30 instruments</option></select><select id="group" aria-label="Asset group"><option value="">All groups</option></select><input id="search" aria-label="Search symbols" placeholder="Find a symbol" size="13"></div></div>
<div class="table-wrap"><table class="asset-table"><thead><tr><th data-sort="symbol">Instrument ↕</th><th data-sort="net">Net return ↕</th><th data-sort="gross">Before costs ↕</th><th data-sort="bh">Buy &amp; hold ↕</th><th data-sort="cagr">Net CAGR ↕</th><th data-sort="dd">Max drawdown ↕</th><th data-sort="bhdd">B&amp;H drawdown ↕</th><th data-sort="trades">Closed trades ↕</th><th data-sort="win">Win rate ↕</th></tr></thead><tbody id="rows"></tbody></table></div>
<p class="note">Returns compound across trades. Figures are per instrument, not portfolio returns. Stock/ETF histories mostly start in 2016; crypto starts in 2021. Current catalog and watchlist flags do not restrict the universe. Group labels use the app’s existing ETF lists; remaining stock-market instruments are labelled Other equities.</p></section>
<section class="panel"><div class="panel-top"><div><h2 id="trade-title">Trades to inspect</h2><div class="sub">Selected instrument. Worst completed trades first; open positions are marked separately in the full ledger.</div></div><a href="trades.csv" download>Download all trades ↗</a></div><div class="table-wrap" id="trades"></div></section>
<section class="panel"><h2>How to read Step 1</h2><div class="reading"><p><strong>1. Start with return and drawdown.</strong>A positive return can still trail holding the asset. Lower drawdown is useful, but examine what return was sacrificed and how long recovery took.</p><p><strong>2. Separate the rules from costs.</strong>The before-cost line uses exactly the same trades. Its gap from net return includes the effect of compounding after costs; the gap is not a sum of fees paid.</p><p><strong>3. Treat this as the starting measurement.</strong>The results describe known history, including indicator warm-up. The next stage can test different entry and exit speeds. Step 1 selects no new parameters.</p></div>
<details open><summary>Measurement and review checks</summary><p id="checks" class="checks"></p><p>CAGR uses elapsed calendar years. Volatility and zero-cash Sharpe use 252 sessions for equities and 365 days for crypto; this differs from the app’s current 252-day convention for crypto. Total returns and trade calculations use the current production engine.</p><p>One position per symbol; units are fixed within a trade. Each new trade deploys the current simulated equity. Uninvested cash earns zero. Stops use daily OHLC and assumed fills; intraday liquidity is not reconstructed. Buy &amp; hold starts at the first stored close. The full-history start includes strategy warm-up in cash.</p><p>The report and raw outputs use one read-only database snapshot. Keep the instruments folder alongside this HTML for local chart data; no external data connection is required. <a href="inputs.csv.gz" download>Input prices · compressed CSV</a> · <a href="daily.csv.gz" download>Daily returns · compressed CSV</a> · <a href="results.json" download>Results &amp; assumptions JSON</a></p></details></section>
<footer>Step 1 is ready for review. Experiment code and report remain in the temp folders.</footer></main>
<script>__PLOTLY__</script><script>
const report=__DATA__, rows=report.summary, meta=report.metadata;
const el=id=>document.getElementById(id), pct=x=>x==null?'—':(100*x).toLocaleString('en-US',{minimumFractionDigits:1,maximumFractionDigits:1})+'%',
 num=x=>x==null?'—':x.toLocaleString('en-US',{maximumFractionDigits:1}), cls=x=>x<0?'negative':'positive';
const colors={net:'#087f7a',gross:'#b8893c',buy_hold:'#5c6a9a',long:'#3097ac',short:'#c36d66'};
const names={net:'Strategy · after costs',gross:'Strategy · before costs',buy_hold:'Buy & hold',long:'Long contribution',short:'Short contribution'};
const layout={paper_bgcolor:'white',plot_bgcolor:'white',font:{family:'Segoe UI, system-ui, sans-serif',size:11,color:'#53696d'},margin:{l:58,r:18,t:40,b:35},hovermode:'x unified',legend:{orientation:'h',x:0,y:1.13},xaxis:{showgrid:false},yaxis:{gridcolor:'#e9efeb',zerolinecolor:'#dfe7e4'}};
const config={responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d'],toImageButtonOptions:{format:'png',scale:2}};
let selected='BTC/USD',sort='symbol',descending=false;
el('stamp').textContent=`${meta.symbol_count} instruments · ${meta.engine_version} · Generated ${meta.generated_utc.slice(0,10)} UTC`;
function renderKpis(view){const count=fn=>view.filter(fn).length;
el('kpis').innerHTML=[['Both directions · positive net',`${count(s=>s.stats.net.total_return>0)} / ${view.length}`,'Long and short trades combined, after costs'],['Long contribution · positive net',`${count(s=>s.stats.long.total_return>0)} / ${view.length}`,'Long trades from that same simulation'],['Short contribution · positive net',`${count(s=>s.stats.short.total_return>0)} / ${view.length}`,'Short trades from that same simulation'],['Trade accounting checked',num(view.reduce((n,s)=>n+s.closed_trades,0)),'Closed trades; open marks also reconciled']].map(([label,value,note])=>`<div class="kpi"><div class="label">${label}</div><strong>${value}</strong><small>${note}</small></div>`).join('');}
el('symbol').innerHTML=rows.map(s=>`<option value="${s.symbol}">${s.symbol} · ${s.group}</option>`).join('');
el('group').innerHTML+=[...new Set(rows.map(s=>s.group))].map(g=>`<option>${g}</option>`).join('');
el('checks').textContent=`${meta.symbol_count} instrument curves reconcile to independently rebuilt fill P&L; ${meta.closed_trades_checked.toLocaleString()} closed trades checked. ${meta.prefix_checks} truncated-history checks confirm that later bars do not change earlier returns at the tested cutoffs. Costed and zero-cost runs have identical fills. BTC and ETH use only Coinbase data, with a candle for every day in their stored periods. These checks validate the measured accounting, not profitability or live fill quality.`;
el('checks').textContent+=` A separate simulator computes its own indicators, signals and fills, and marks signed units plus cash on ${meta.independent_cash_bars.toLocaleString()} daily observations. It agrees with production equity within numerical rounding, stopping at account exhaustion (ECHO).`;
function renderTable(){
const key=s=>({symbol:s.symbol,net:s.stats.net.total_return,gross:s.stats.gross.total_return,bh:s.stats.buy_hold.total_return,cagr:s.stats.net.cagr,dd:s.stats.net.max_drawdown,bhdd:s.stats.buy_hold.max_drawdown,trades:s.closed_trades,win:s.win_rate}[sort]);
const visible=rows.filter(s=>(el('scope').value==='all'||s.watchlist)&&(!el('group').value||s.group===el('group').value)&&s.symbol.toLowerCase().includes(el('search').value.toLowerCase())).sort((a,b)=>{const x=key(a),y=key(b);if(x==null)return 1;if(y==null)return -1;return (typeof x==='string'?x.localeCompare(y):x-y)*(descending?-1:1)});
renderKpis(visible);
el('rows').innerHTML=visible.map(s=>`<tr data-symbol="${s.symbol}" class="${s.symbol===selected?'selected':''}"><td class="asset">${s.symbol}<small>${s.start} → ${s.end}</small>${s.stats.net.insolvency_date?'<small style="color:#bc4b49">Equity exhausted · raw curve</small>':''}</td><td class="${cls(s.stats.net.total_return)}">${pct(s.stats.net.total_return)}</td><td>${pct(s.stats.gross.total_return)}</td><td>${pct(s.stats.buy_hold.total_return)}</td><td class="${cls(s.stats.net.cagr)}">${pct(s.stats.net.cagr)}</td><td>${pct(s.stats.net.max_drawdown)}</td><td>${pct(s.stats.buy_hold.max_drawdown)}</td><td>${s.closed_trades}</td><td>${pct(s.win_rate)}</td></tr>`).join('');
el('rows').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>{choose(tr.dataset.symbol);el('asset-title').scrollIntoView({behavior:'smooth',block:'start'})});}
function choose(symbol){selected=symbol;el('symbol').value=symbol;renderTable();renderDetail();}
async function renderDetail(){
const requested=selected,s=rows.find(r=>r.symbol===requested),p=s.params;
window.baselineDetails=window.baselineDetails||{};
if(!window.baselineDetails[requested]){try{await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=report.detail_files[requested];script.onload=resolve;script.onerror=reject;document.body.appendChild(script)})}catch(e){el('asset-meta').textContent='Could not load instrument data. Keep the instruments folder alongside report.html.';return}}
if(selected!==requested)return;
const d=window.baselineDetails[requested];
el('instrument-warning').hidden=!s.stats.net.insolvency_date;
if(s.stats.net.insolvency_date){el('instrument-warning').textContent=`Simulated equity fell below zero on ${s.stats.net.insolvency_date}. This is the current engine's raw accounting curve; trading after that date does not model a viable funded account. CAGR is undefined. The instrument remains included in the baseline.`;el('log').checked=false}
el('asset-title').textContent=selected+' · current strategy';el('asset-meta').textContent=`${s.start} → ${s.end} · ${s.bars.toLocaleString()} bars · ${s.source}`;
el('badges').innerHTML=[`${p.entry_len}-bar entry`,`${p.exit_len}-bar channel exit`,`${p.atr_stop_mult}× ATR initial stop`,`${p.chandelier_k}× ATR Chandelier`,'Both directions'].map(x=>`<span class="chip">${x}</span>`).join('');
el('detail-cards').innerHTML=[['Net total return',pct(s.stats.net.total_return),s.stats.net.total_return],['Buy & hold',pct(s.stats.buy_hold.total_return),s.stats.buy_hold.total_return],['Net CAGR',pct(s.stats.net.cagr),s.stats.net.cagr],['Worst drawdown',pct(s.stats.net.max_drawdown),s.stats.net.max_drawdown],['Median cost / fill',num(s.median_fill_cost_bps)+' bps',0]].map(([label,value,color])=>`<div class="detail-card"><span>${label}</span><b class="${color===0?'':cls(color)}">${value}</b></div>`).join('');
Plotly.react('equity',Object.keys(names).map(key=>({x:d.dates,y:d.equity[key].map(v=>v*100),type:'scatter',mode:'lines',name:names[key],line:{color:colors[key],width:key==='net'?2.4:1.6,dash:key==='gross'?'dot':'solid'},visible:key==='long'||key==='short'?'legendonly':true,hovertemplate:'%{y:,.2f}<extra>%{fullData.name}</extra>'})),{...layout,yaxis:{...layout.yaxis,type:el('log').checked?'log':'linear',title:{text:'Value of 100'}}},config);
Plotly.react('drawdown',['net','buy_hold'].map(key=>({x:d.dates,y:d.drawdown[key].map(v=>v*100),type:'scatter',mode:'lines',name:names[key],fill:key==='net'?'tozeroy':undefined,line:{color:colors[key],width:1.5},fillcolor:'rgba(8,127,122,.10)',hovertemplate:'%{y:.1f}%<extra>%{fullData.name}</extra>'})),{...layout,showlegend:false,margin:{l:58,r:18,t:5,b:30},yaxis:{...layout.yaxis,title:{text:'Drawdown %'},ticksuffix:'%'}},config);
Plotly.react('annual',['net','gross','buy_hold'].map(key=>({x:d.annual.map(a=>a.year),y:d.annual.map(a=>a[key]*100),type:'bar',name:names[key],marker:{color:colors[key]},hovertemplate:'%{y:.1f}%<extra>%{fullData.name}</extra>'})),{...layout,barmode:'group',margin:{l:48,r:10,t:45,b:35},legend:{...layout.legend,font:{size:10}},yaxis:{...layout.yaxis,ticksuffix:'%'}},config);
el('cost-note').textContent=`The compounded gap between before-cost and net return is ${num(s.cost_drag_pp)} percentage points. Typical modelled cost per fill is ${num(s.median_fill_cost_bps)} bps, including the ATR component. An open position has its entry cost booked and is marked to the final close, without a hypothetical exit fee.`;
el('sides').innerHTML='<table><thead><tr><th>Direction</th><th>Contribution</th><th>Closed</th><th>Win rate</th></tr></thead><tbody>'+['long','short'].map(key=>`<tr><td>${key==='long'?'Long':'Short'}</td><td class="${cls(s.stats[key].total_return)}">${pct(s.stats[key].total_return)}</td><td>${s.side_trade_stats[key].closed_trades}</td><td>${pct(s.side_trade_stats[key].win_rate)}</td></tr>`).join('')+'</tbody></table><p class="note">Combine factors, not percentage sums: (1 + long return) × (1 + short return) − 1 = combined return.</p>';
const reasonNames={stop_initial:'Initial stop',stop_trailing:'Trailing stop',channel_reversal:'Channel exit'};
el('exits').innerHTML=Object.entries(s.exit_reasons).map(([key,n])=>`<p class="sub">${reasonNames[key]||key}: <b>${n}</b> · ${pct(n/s.closed_trades)}</p>`).join('');
el('recovery').textContent=`Longest period below a prior equity peak: ${s.stats.net.longest_underwater_calendar_days.toLocaleString()} calendar days. ${s.stats.net.unrecovered?'The final equity remains below its previous peak.':'The final equity is at a high.'} Average completed holding period: ${num(s.average_hold_bars)} bars. Open position: ${s.open_position||'none'}.`;
el('params').innerHTML=Object.entries(p).map(([key,value])=>`<div>${key}: <b>${value}</b></div>`).join('');el('accounting').textContent=meta.position_model+'. '+meta.annualisation+'.';
el('trade-title').textContent=selected+' · trades to inspect';
el('trades').innerHTML='<table><thead><tr><th>Direction</th><th>Entry</th><th>Exit</th><th>Entry price</th><th>Exit price</th><th>Net trade</th><th>Exit reason</th><th>Bars held</th></tr></thead><tbody>'+d.trades.filter(t=>t.exit_date).sort((a,b)=>a.marked_net_return-b.marked_net_return).slice(0,8).map(t=>`<tr><td>${t.direction}</td><td>${t.entry_date}</td><td>${t.exit_date}</td><td>${num(t.entry_price)}</td><td>${num(t.exit_price)}</td><td class="${cls(t.marked_net_return)}">${pct(t.marked_net_return)}</td><td>${reasonNames[t.exit_reason]||t.exit_reason}</td><td>${t.bars_held}</td></tr>`).join('')+'</tbody></table>';
}
el('symbol').onchange=()=>choose(el('symbol').value);el('log').onchange=renderDetail;el('scope').onchange=renderTable;el('group').onchange=renderTable;el('search').oninput=renderTable;
document.querySelectorAll('[data-sort]').forEach(th=>th.onclick=()=>{descending=sort===th.dataset.sort?!descending:true;sort=th.dataset.sort;renderTable()});
choose(selected);
</script></body></html>'''
