async (page) => {
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const ready=()=>page.waitForFunction(()=>document.querySelector('#status').textContent.includes('assets retained'));
  await page.reload();await ready();
  await page.setViewportSize({width:1440,height:1050});
  await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'docs/temp/step6/review-desktop.png',fullPage:false});
  const desktop=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,charts:document.querySelectorAll('.js-plotly-plot').length,status:document.querySelector('#status').textContent}));
  if(desktop.scroll>desktop.width||desktop.charts!==5)throw new Error('Desktop overflow or missing charts');
  await page.locator('#scope').selectOption('universe');await ready();
  await page.locator('#book').selectOption('short-reference');await ready();
  await page.locator('#cost').selectOption('double');await ready();
  await page.locator('#asset').selectOption('BTC/USD');
  const short=await page.locator('#assetStats').innerText();
  const shortTradeRows=await page.locator('#trades tbody tr').count();
  if(!shortTradeRows)throw new Error('Short BTC ledger missing');
  await page.locator('#book').selectOption('combined-initial');await ready();
  await page.locator('#method').selectOption('capped-vol');await ready();
  await page.locator('#asset').selectOption('ETH/USD');
  const sides=await page.locator('#trades tbody tr td:first-child').allTextContents();
  if(!sides.includes('long')||!sides.includes('short'))throw new Error('Combined ETH ledger must show both directions');
  await page.locator('#search').fill('HONA');
  await page.locator('#assetTable tbody tr').click();
  const insufficient=await page.locator('#assetStats').innerText();
  if(await page.locator('#trades tbody tr').count()!==0)throw new Error('Insufficient-history asset has funded trades');
  await page.locator('#search').fill('');
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#download').click();
  const download=await downloadPromise;
  await page.locator('#book').selectOption('buy-hold');await ready();
  if(!await page.locator('#method').isDisabled())throw new Error('Buy/hold must use its fixed reference allocation');
  await page.locator('#scope').selectOption('priority');await ready();
  await page.locator('#book').selectOption('long-initial');await ready();
  await page.locator('#cost').selectOption('normal');await ready();
  await page.locator('#method').selectOption('inverse-vol');await ready();
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'docs/temp/step6/review-mobile.png',fullPage:false});
  const mobile=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,status:document.querySelector('#status').textContent}));
  if(mobile.scroll>mobile.width)throw new Error('Mobile page overflow');
  await page.locator('#equity').scrollIntoViewIfNeeded();
  await page.screenshot({path:'docs/temp/step6/review-mobile-charts.png',fullPage:false});
  if(errors.length)throw new Error(errors.join('\n'));
  return {desktop,mobile,shortTradeRows,short,combinedSides:[...new Set(sides)],insufficient,download:download.suggestedFilename(),errors};
}
